### PR TITLE
Fix several issues and improve performance

### LINKED ISSUE #21: Growing files break tar files
If a file grows while it is processed, the header's file size does not match the written file length.

Imho we should stop writing data after the file size written to the header has been reached:
https://github.com/thilo-schmitt/tarxx/blob/861fb4d0872fc2580f7a9d6fefee5ac5b45441b0/include/tarxx.h#L870-L883

### PR DESCRIPTION
**Pull request by alexmohr**
* properly handle files which change in size during archiving
* deal with symlinks properly by not making their destination relative
* increase performance by factor 3
* handle blocks with size 0 properly
* thread safety: use thread safe posix functions

fixes #21 

<sup>Alexander Mohr, <alexander.m.mohr@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

### CODE REVIEW

File: include/tarxx.h [hunk 1]
```diff
@@ -816,12 +851,13 @@ namespace tarxx {
             major_t dev_major = 0;
             minor_t dev_minor = 0;
             std::string link_name;
-            std::string file_name = target_path;
+            const std::string& file_name = target_path;
```
Comment (thilo-schmitt) [inline include/tarxx.h]: If I'm not mistaken neither `file_name` nor `target_path` is used in this function (anymore). please remove.
`target_path` not being used seems fishy, though...

File: tests/util/util.h [hunk 2]
```diff
@@ -77,7 +77,7 @@ namespace util {
     template<typename... T, typename = std::enable_if<is_homogeneous_type_v<char*, T...>>>
     inline int execute(const std::string& cmd, T*... args)
     {
-#if defined(__linux)
+#if defined(__linux)
```
Comment (thilo-schmitt) [inline tests/util/util.h]: no trailing whitespace, please.

File: tests/util/util.h [hunk 3]
```diff
@@ -96,7 +96,7 @@ namespace util {
 
     inline int execute_with_output(const std::string& cmd, std::string& std_out)
     {
-#if defined(__linux)
+#if defined(__linux)
```
Comment (thilo-schmitt) [inline tests/util/util.h]: no trailing whitespace, please.

File: include/tarxx.h [hunk 4]
```diff
@@ -391,6 +407,44 @@ namespace tarxx {
...
+            const auto iter = group_buffer_.find(gid);
+            if (iter != group_buffer_.end()) {
+                return iter->second;
+            }
+            const auto* const groupPtr = getgrgid(gid);
+            std::string name;
+            if (groupPtr == nullptr) {
+                name = std::to_string(gid);
+            } else {
+                name = groupPtr->gr_name;
```
Comment (thilo-schmitt) [inline include/tarxx.h]: Do we need to protect against `groupPtr->gr_name` being `NULL`?

File: include/tarxx.h [hunk 5]
```diff
@@ -391,6 +407,44 @@ namespace tarxx {
...
+            const auto iter = user_buffer_.find(uid);
+            if (iter != user_buffer_.end()) {
+                return iter->second;
+            }
+            const auto* const userPtr = getpwuid(uid);
+            std::string name;
+            if (userPtr == nullptr) {
+                name = std::to_string(uid);
+            } else {
+                name = userPtr->pw_name;
```
Comment (thilo-schmitt) [inline include/tarxx.h]: Do we need to protect against `userPtr->pw_name` being `NULL`?

File: include/tarxx.h [hunk 6]
```diff
@@ -391,6 +407,44 @@ namespace tarxx {
             if (stat_res != 0) throw errno_exception();
             return file_stat;
         }
+
+    private:
+        std::unordered_map<gid_t, std::string> group_buffer_;
+        std::unordered_map<uid_t, std::string> user_buffer_;
```
Comment (thilo-schmitt) [inline include/tarxx.h]: aren't those rather "caches" (instead of "buffers")?

File: include/tarxx.h [hunk 7]
```diff
@@ -828,42 +922,54 @@ namespace tarxx {
...
         {
             if (!platform_.file_exists(source_path)) throw std::invalid_argument(source_path + " does not exist");
             if (source_path == file_name_) throw std::invalid_argument("tar cannot be part of itself");
 
             std::function<void()> write_data;
+            auto file_type = platform_.type_flag(source_path);
+            std::string resolved_source_path;
+            if (file_type == file_type_flag::SYMBOLIC_LINK && read_symlinks) {
+                resolved_source_path = platform_.realpath(source_path);
+                if (!platform_.file_exists(resolved_source_path)) throw std::invalid_argument(resolved_source_path + " does not exist");
```
Comment (thilo-schmitt) [inline include/tarxx.h]: Hm, the user catching this exception might be surprised by the filename it contains since the inputted `source_path` will be different. We might want to give a hint that we tried to follow the symlink and the linked file didn't exist.

File: include/tarxx.h [hunk 8]
```diff
@@ -436,41 +491,81 @@ namespace tarxx {
...
+        // delete the copy constructor and copy assignment, as multiple instances to the same file are not supported
+        tarfile(const tarfile&) = delete;
+        tarfile& operator=(const tarfile& other) = delete;
+
+        tarfile(tarfile&& other) noexcept
+        {
+            *this = std::move(other);
+        }
+
+        tarfile& operator=(tarfile&& other) noexcept
```
Comment (thilo-schmitt) [inline include/tarxx.h]: Hmm, this doesn't seem correct. Files will be closed after the move-assignment. This is semantically unexpected, I'd argue. How can we make this a "real" move?

File: include/tarxx.h [hunk 9]
```diff
@@ -599,36 +598,9 @@ namespace tarxx {
...
-            stream_file_header_pos_ = other.stream_file_header_pos_;
-            stream_block_ = other.stream_block_;
-            stream_block_used_ = other.stream_block_used_;
-
-            platform_ = std::move(other.platform_);
-            stored_inos_ = std::move(stored_inos_);
-            other.close();
-            return *this;
-        }
+        tarfile& operator=(const tarfile&& other) = delete;
```
Comment (thilo-schmitt) [inline include/tarxx.h:603]: Nevermind my previous comment about `tarfile`'s move-assignment being semantically bad. You deleted it here. Good!
Of course it would be great if you'd transplanted this into the earlier commit, but I'll not insist :)

**Review by thilo-schmitt — CHANGES_REQUESTED** [review]
Thank you for submitting the PR. I'm sincerely sorry that I didn't get to review it earlier.
I commented a few small things. Let me know what you think.

File: include/tarxx.h (hunk 1 above)
Comment (alexmohr) [reply include/tarxx.h]: `file_name` is used when calling `write_header` in line 1061

File: tests/util/util.h (hunk 2 above)
Comment (alexmohr) [reply tests/util/util.h]: This comment is based on an outdated version of the file. If you insist I'll fix it on the commit this comment is based on but on the head of the branch this issue does not exist anymore.

File: tests/util/util.h (hunk 3 above)
Comment (alexmohr) [reply tests/util/util.h]: This comment is based on an outdated version of the file. If you insist I'll fix it on the commit this comment is based on but on the head of the branch this issue does not exist anymore.

File: include/tarxx.h (hunk 4 above)
Comment (alexmohr) [reply include/tarxx.h]: On the latest version `getgrgid_r` is used. 
``` 
The string fields pointed to by the members of the group structure are stored in the buffer buf of size buflen. A pointer to the result (in case of success) or NULL (in case no entry was found or an error occurred) is stored in *result.
```

So yes the pointer might be null

File: include/tarxx.h (hunk 5 above)
Comment (alexmohr) [reply include/tarxx.h]: Same reasoning as https://github.com/thilo-schmitt/tarxx/pull/22#discussion_r1444001369

File: include/tarxx.h (hunk 6 above)
Comment (alexmohr) [reply include/tarxx.h]: isn't a cache just buffering values until they are required again?
But yes it's a cache. Should I rename it accordingly?

File: include/tarxx.h (hunk 8 above)
Comment (alexmohr) [reply include/tarxx.h]: The operator has been deleted in the latest version. Moving the tarfile opened a can of worms with a ton of gotchas which I wanted to prevent by deleting the operator entirely.

File: include/tarxx.h (hunk 7 above)
Comment (alexmohr) [reply include/tarxx.h]: Makes sense
Changed message to
```c++
throw std::invalid_argument("source_path " + source_path + " is a symlink pointing to " + resolved_source_path + " which does not exist");
```

File: include/tarxx.h (hunk 9 above)
Comment (alexmohr) [reply include/tarxx.h:603]: If you don't insist I won't transplant it :+1:

File: include/tarxx.h (hunk 6 above)
Comment (thilo-schmitt) [reply include/tarxx.h]: To me a buffer and a cache are different things for different purposes. I'd prefer naming them caches here. If it's too much work now, we can still fix it later.

File: include/tarxx.h (hunk 4 above)
Comment (thilo-schmitt) [reply include/tarxx.h]: I see. Nevermind :-)

File: include/tarxx.h (hunk 5 above)
Comment (thilo-schmitt) [reply include/tarxx.h]: I see. Nevermind :-)

File: include/tarxx.h (hunk 6 above)
Comment (alexmohr) [reply include/tarxx.h]: Sure, renamend to `grpid_cache_`  and `pwuid_cache_`

File: include/tarxx.h (hunk 1 above)
Comment (alexmohr) [reply include/tarxx.h]: do you need further input here or can this thread be resolved?

File: include/tarxx.h (hunk 6 above)
Comment (thilo-schmitt) [reply include/tarxx.h]: thank you!

File: include/tarxx.h (hunk 1 above)
Comment (thilo-schmitt) [reply include/tarxx.h]: why can't `target_path` be used directly down there?

Comment (alexmohr) [reply include/tarxx.h]: it can, and it is now :)

**Comment by thilo-schmitt** [comment]
Thank you for bearing with me. Looks good now. Will merge.
